### ISSUE TITLE
File Manager Depend

### ISSUE THREAD

**Issue by VB10** [chillxcode/dolap-ios-case-study#4]
Bu sınıfın constructor da IFıleManager alıp instance sayfadan yolla
https://github.com/chillxcode/dolap-ios-case-study/blob/c057933ed6a23bde67564e0eabe5af46b02f43da/dolap-ios-case-study/Controller/ProductDetail/ProductDetailWorker.swift#L11

**Comment by chillxcode** [comment]
fixed
